filebeat.inputs:
  - type: log
    paths:
      - /var/lib/mysql/*.log
    fields:
      app_id: "mysql"
  - type: kafka
    fields:
      app_id: "missyou_sinry"
    hosts:
      - kafka-springboot-log-1:9092
    topics: ["kafka-springboot-log-1"]
    group_id: "kafka-springboot-log-1"
output.logstash:
  hosts: ["logstash:5044"]
#output.console:
#  pretty: true
