filebeat.inputs:
  - type: log
    paths:
      - /var/lib/mysql/*.log
    fields:
      es_index: "mysql"
#  - type: springboot
#    hosts:
#      - kafka-broker-1:9092
#      - kafka-broker-2:9092
#      topics: ["my-topic"]
#      group_id: "filebeat"
output.logstash:
  hosts: ["logstash:5044"]
#output.console:
#  pretty: true
