spring:
  profiles:
    active: ${JAVA_ENV:dev}
  jpa:
    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #use_sql_comments: true
sinry:
  api-package: com.sinry.demo.api