spring:
  profiles:
    active: ${JAVA_ENV:dev}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #use_sql_comments: true
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 0
    # redis连接池配置
    pool:
    # 最大可用连接数（默认为8，负数表示无限）
    max-active: 8
    # 最大空闲连接数（默认为8，负数表示无限）
    max-idle: 8
    # 最小空闲连接数（默认为0，该值只有为正数才有作用）
    min-idle: 0
    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
    max-wait: -1
  application:
    name: com.sinry.missyou
sinry:
  api-package: com.sinry.missyou.api
  filter-map:
mysql:
  ip: 192.168.1.1
  port: 3306
logging:
  file:
#    name: springboot-loggers.log
    path: ./logs
    max-size: 100MB
    max-history: 7
  config: classpath:logback-spring.xml
  level:
    root: info
logstash:
  host: 192.168.1.10
  port: 9600
server:
  tomcat:
    accesslog:
      max-days: 5 #日志保留天数